[package]
name = "sms-data-clean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stopwords = "0.1.1"
smartcore = { version = "*", default-features = false, features = ["serde"] }
